---
- name: Network get info
  connection: network_cli
  hosts: cisco    # 指定inventory里的host或host group
  tasks:
    - name: Get cofig
      ios_facts:    # module
        gather_subset: all
        
    - name: Display hostname
      debug:        # module
        msg: 
          - "The hostname is: {{ ansible_net_hostname }}"
          - "The model is: {{ ansible_net_serialnum }}"
          - "{{ ansible_net_all_ipv4_addresses }}"
          
    - name: Config hostname
      ios_system:   # module
        hostname: "{{ inventory_hostname }}" 
