---
- name: Network get info
  connection: network_cli
  hosts: cisco
  tasks:
    - name: Get cofig
      ios_facts:
        gather_subset: all
    - name: Display hostname
      debug:
        msg: 
          - "The hostname is: {{ ansible_net_hostname }}"
          - "The model is: {{ ansible_net_serialnum }}"
          - "{{ ansible_net_all_ipv4_addresses }}"
    - name: Config hostname
      ios_system:
        hostname: "{{ inventory_hostname }}" 
