---
- name: Network get info
  connection: network_cli
  hosts: cisco    # 指定inventory里的host或host group
  tasks:
    - name: Get config
      ios_facts:    # module
        gather_subset: all
        
    - name: Display hostname
      debug:        # module
        msg: 
          - "The hostname is: {{ ansible_net_hostname }}"
          - "The model is: {{ ansible_net_serialnum }}"
          - "{{ ansible_net_all_ipv4_addresses }}"
          
    - name: Config hostname
      ios_system:   # module
        hostname: "{{ inventory_hostname }}"   # 根据inventory里定义的hostname
        
    - name: show run
      ios_command:
        commands:
          - show run
      register: config  # 注冊變量config，給其他task調用
      
    - name: Save output to file
      copy:
        content: "{{ config.stdout[0] }}"  # 調用上一個task的變量config
        dest: "/home/pi/ansible/config/{{ inventory_hostname }}.txt"
